// Writes src/abi/<contract>.ts from the Foundry artifacts in contracts/out.
//
//   cd contracts && forge build --force
//   pnpm --filter @spillway/web abi
//
// The ABIs are committed so the app builds without a Solidity toolchain. `as const` lets
// viem type every read, write and event from them.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "contracts", "out");
const target = join(here, "..", "src", "abi");

// [artifact, file in src/abi, exported name]. Morpho is the official Morpho Blue build.
const contracts = [
  ["MorphoCoverVault", "vault", "vaultAbi"],
  ["MockUSD", "usd", "usdAbi"],
  ["MockOracle", "oracle", "oracleAbi"],
  ["Morpho", "morpho", "morphoAbi"],
] as const;

mkdirSync(target, { recursive: true });
for (const [name, file, constName] of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8")) as { abi: unknown };
  const body = `// Generated by scripts/abi.ts from contracts/out/${name}.sol. Do not edit by hand.\n\nexport const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(target, `${file}.ts`), body);
  console.error(`wrote src/abi/${file}.ts`);
}
