// Writes src/abi.ts from the Foundry artifacts in contracts/out.
//
//   cd contracts && forge build
//   pnpm --filter @spillway/watcher abi
//
// The ABIs are committed so the watcher typechecks without a Solidity toolchain.
// Bytecode is not: the e2e script reads it from contracts/out when it deploys.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "contracts", "out");
const target = join(here, "..", "src", "abi.ts");

const contracts = [
  ["MockUSD", "mockUsdAbi"],
  ["MockBackstopAdapter", "adapterAbi"],
  ["CoverVault", "vaultAbi"],
] as const;

let body = "// Generated by scripts/extract-abi.ts from contracts/out. Do not edit by hand.\n";
for (const [name, constName] of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8")) as { abi: unknown };
  body += `\nexport const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
writeFileSync(target, body);
console.error(`wrote ${target}`);
